// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBHMPItmw0gLhQD1OB0BmnvwTLAofsEqg',
    appId: '1:432963026298:web:408fb15d083be1f73c2ac3',
    messagingSenderId: '432963026298',
    projectId: 'typocalypse-v1',
    authDomain: 'typocalypse-v1.firebaseapp.com',
    storageBucket: 'typocalypse-v1.firebasestorage.app',
    measurementId: 'G-8RWRDV187S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCivhkR-h1dMl0aQnj03UpJbu3OgMnnRYI',
    appId: '1:432963026298:android:092a63d425e8f5073c2ac3',
    messagingSenderId: '432963026298',
    projectId: 'typocalypse-v1',
    storageBucket: 'typocalypse-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRXKucM-HGGIA3GGb411Q_fuDoD-gmS8Q',
    appId: '1:432963026298:ios:de488d68225d30cd3c2ac3',
    messagingSenderId: '432963026298',
    projectId: 'typocalypse-v1',
    storageBucket: 'typocalypse-v1.firebasestorage.app',
    iosBundleId: 'com.example.typocalypse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRXKucM-HGGIA3GGb411Q_fuDoD-gmS8Q',
    appId: '1:432963026298:ios:de488d68225d30cd3c2ac3',
    messagingSenderId: '432963026298',
    projectId: 'typocalypse-v1',
    storageBucket: 'typocalypse-v1.firebasestorage.app',
    iosBundleId: 'com.example.typocalypse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBHMPItmw0gLhQD1OB0BmnvwTLAofsEqg',
    appId: '1:432963026298:web:cbcbdea090cc90b63c2ac3',
    messagingSenderId: '432963026298',
    projectId: 'typocalypse-v1',
    authDomain: 'typocalypse-v1.firebaseapp.com',
    storageBucket: 'typocalypse-v1.firebasestorage.app',
    measurementId: 'G-17B9G80KXC',
  );
}
